### ISSUE TITLE
建议vmessConfig()中alterId参数设置为0

### ISSUE THREAD

**Issue by Mega-Ryan** [Misaka-blog/Xray-script#1]
![image](https://user-images.githubusercontent.com/61368962/156917803-2d0630ae-cade-44b2-b841-15c2dc5c19a7.png)
上图来自xray 1.5.3更新说明(https://github.com/XTLS/Xray-core/releases/tag/v1.5.3) ，自1月1日起强制启用VMESS AEAD，即需要将客户端alterId设置为默认值0才能正常使用。
本脚本中alterId为50--80的随机数，生成vmess链接并导入客户端后，客户端alterId也是50--80的随机数，会导致服务器不能正常转发流量，需要手动将alterId改为0后才能正常使用，会对部分新手用户造成困扰。
建议直接将alterId设置为0，避免此类问题。

**Comment by misakano7545** [comment]
好的，我会注意

**Comment by misakano7545** [comment]
已修复！
