### ISSUE TITLE
安装XRAY问题1

### ISSUE THREAD

**Issue by freewzq** [Misaka-blog/Xray-script#7]
@Hi,Misaka:

感谢您的脚本及分享。
在运行安装时提示vultr.cnlinkjp.life 解析结果：45.76.237.216
域名未解析到当前服务器IP(2001:19f0:6401:1f79:5400:3ff:fef8:ee9f)！
可是我检查已经解析了，域名注册在namesilo,请问问题出在哪里？

谢谢

**Comment by LYwyc** [comment]
把vps的ipv6地址关掉，只解析ipv4地址，或者用此脚本把ipv6地址关掉
