### ISSUE TITLE
请教一下关于bot的问题

### ISSUE THREAD

**Issue by KunG0100** [Misaka-blog/Xray-script#9]
队列服务是正常的，查流量那些功能也正常，但推送工单的功能报错了，以下是完整的信息截图，麻烦佬帮我看一下是什么原因，感谢～
![image](https://user-images.githubusercontent.com/105715752/170616719-63ab8a1a-3f8c-4237-bca7-e754651b7395.jpeg)

**Comment by misakano7545** [comment]
@KunG0100 和后端无关
